-- 코드를 입력하세요
SELECT DISTINCT(a.CAR_ID) AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS a
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS b on a.CAR_ID = b.CAR_ID
WHERE CAR_TYPE LIKE '%세단%' AND MONTH(START_DATE) = 10
ORDER BY a.CAR_ID DESC